"""
captioner
=========

A small, self-contained image captioning toolkit.

If an API key for OpenAI (GPT-4) vision models is available in the
environment, captions are generated by sending the image to that model.
Anthropic (Claude) is also supported as an alternative backend (set
ANTHROPIC_API_KEY). Otherwise the package falls back to a "demo mode" that
produces a template-based caption using classic image-processing heuristics
(dominant colors, brightness, orientation, edge/complexity estimate) -- no
real object recognition is performed in demo mode.
"""

from .heuristics import generate_heuristic_caption, analyze_image
from .llm import generate_caption, get_active_backend

__all__ = [
    "generate_heuristic_caption",
    "analyze_image",
    "generate_caption",
    "get_active_backend",
]

__version__ = "1.0.0"
